// Anish
$(document).ready(function(){
	$('.hamburger-shell').click(function(){
		$('#menu').slideToggle(300);
		$('.top').toggleClass('rotate');
		$('.middle').toggleClass('rotate-back');
		$('.menu-name').toggleClass('bump');
		$('.bg-cover').toggleClass('reveal');
	});
	$('.bg-cover').click(function(){
		$('#menu').slideToggle(300);
		$('.top').toggleClass('rotate');
		$('.middle').toggleClass('rotate-back');
		$('.menu-name').toggleClass('bump');
		$('.bg-cover').toggleClass('reveal');
	})
	$(window).scroll(function(){
		$('#menu').slideUp(300);
		$('.top').removeClass('rotate');
		$('.middle').removeClass('rotate-back');
		$('.menu-name').removeClass('bump');
		$('.bg-cover').removeClass('reveal');
	})
});